[package]
name = "pass"
version = "0.1.0"
edition = "2021"
authors = [ "Mark Wilkerson <cargo@markhuge.com>" ]
description = "parse password-store entries"
license = "LGPL-2.1"

[dependencies]
serde = {version = "1.0.138", features = ["derive"]}
